name: Super Linter Python
on:
  pull_request:
    branches:
      - main
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step Super Linter Python
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
